
name: Update README Activity

on:
  workflow_dispatch:        # 手動觸發
  schedule:
    - cron: '0 */12 * * *'  # 每 12 小時跑一次（UTC）

permissions:
  contents: write           # 只給寫入內容的權限

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate activity section
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用內建 Token，避免 PAT 問題
          REPO: ${{ github.repository }}
        run: |
          SINCE=$(date -u -d '7 days ago' +%FT%TZ)
          {
            echo "### Recent Activity (last 7 days)"
            echo ""
            echo "**Recent Commits**"
            gh api repos/$REPO/commits --paginate -f since="$SINCE" \
              -q '.[] | "- " + .sha[0:7] + " " + .commit.message | gsub("\\n"; " ")' | head -n 5
            echo ""
            echo "_Last updated: $(date -u +%FT%TZ)_"
          } > activity.md

          START='<!--START_SECTION:activity-->'
          END='<!--END_SECTION:activity-->'
          awk -v start="$START" -v end="$END" '
            $0 ~ start {print; while ((getline l < "activity.md") > 0) print l; close("activity.md"); in=1; next}
            $0 ~ end   {print; in=0; next}
            !in {print}
          ' README.md > README.new && mv README.new README.md

      - name: Commit & Push
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README activity"
          git push
