
name: Update README Activity (Minimal)

on:
  workflow_dispatch:          # 手動觸發
  schedule:
    - cron: '0 */12 * * *'    # 每 12 小時（UTC）

permissions:
  contents: write             # 只需寫入內容

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure markers exist
        run: |
          set -e
          START='<!--START_SECTION:activity-->'
          END='<!--END_SECTION:activity-->'
          if ! grep -q "$START" README.md || ! grep -q "$END" README.md; then
            echo "::error::README.md 缺少標記區塊。請加入以下兩行："
            echo "$START"
            echo "$END"
            exit 1
          fi

      - name: Generate activity (last 7 days) with git log
        run: |
          set -e
          {
            echo "### Recent Activity (last 7 days)"
            echo ""
            echo "**Recent Commits**"
            # 顯示最近 7 天、最多 5 筆提交（若沒有就顯示 (none)）
            if git log --since='7 days ago' --pretty='- %h %s' -n 5 | sed '/^$/d' | tee /dev/stderr | grep -q '^- '; then
              git log --since='7 days ago' --pretty='- %h %s' -n 5
            else
              echo "- (none)"
            fi
            echo ""
            echo "_Last updated: $(date -u +%FT%TZ)_"
          } > activity.md

      - name: Replace README section between markers (sed)
        run: |
          set -e
          START='<!--START_SECTION:activity-->'
          END='<!--END_SECTION:activity-->'
          # 用 sed 在標記之間插入 activity.md，並刪掉舊內容
          sed -e "/$START/,/$END/{
            /$START/{
              p
              r activity.md
            }
            /$END/p
            d
          }" README.md > README.new
          mv README.new README.md

      - name: Commit & Push if changed
        run: |
          set -e
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: auto-update README activity (minimal)"
          git push
